version: "2.1"
services:
  neptune:
    image: ghcr.io/codel1417/neptune-discord-bot:master
    environment:
      - NEPTUNE_TOKEN=null
      - NEPTUNE_TENOR_TOKEN=null
    volumes:
      - ./Media:/nep/Media
    restart: unless-stopped
