version: "2.1"
services:
  Neptune_Core:
    image: codel1417/bot
    environment:
      - botToken=
      - tenorToken=
    volumes:
      - ./Logs:/nep/Logs
      - ./Guilds:/nep/Guilds
      - ./Media:/nep/Media
    restart: unless-stopped