version: "2.1"
services:
  Neptune_Core:
    build: .
    environment:
      - NEPTUNE_TOKEN=null
      - NEPTUNE_TENOR_TOKEN=null
      - SENTRY_DSN=http://43e14c45d81c4c9290bc449d705d2062@docker-vm.codel1417.lan:7000/2
    volumes:
      - ./Logs:/nep/Logs
      - ./Guilds:/nep/Guilds
      - ./Media:/nep/Media
      - ./tessdata:/nep/tessdata
    restart: unless-stopped
    # Temperary fix for jstatd not working
    user: "0"
    command: "./gradlew run"
    networks:
      - prometheus
      - db
      - redis
    ports:
      - 11234:1234
      - 11233:1233
      - 11232:1232
    depends_on:
      db:
        condition: service_healthy
  db:
    image: ghcr.io/linuxserver/mariadb
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      - TZ=America/Phoenix
      - MYSQL_DATABASE=neptune
      - MYSQL_USER=neptune
      - MYSQL_PASSWORD=neptune
    volumes:
      - ./mysql:/config
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - db
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    command: redis-server --requirepass jsZSc4p9D3jRj5
    volumes:
      - ./redis:/data
    networks:
      - redis
networks:
  db:
  redis:
  prometheus:
    external:
      name: prometheus