name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.1.0
        with:
          context: .
          file: ./Dockerfile.build
          # List of tags
          tags: 
            codel1417/bot:latest
            codel1417/bot:${GITHUB_SHA}
          push: ${{ github.event_name != 'pull_request' }}
